apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: default
spec:
  kafka:
    version: 2.5.0
    replicas: 3 
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: '2.5'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: sample 
  namespace: default
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10 
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
